title: Almansur Kakimov
description: Researcher in AI-Driven Intelligent Wireless Networks for 5G/6G.
url: "https://almansur04.github.io"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md
  - LICENSE
